name: Scheduled data update
on:
  schedule:
    - cron:  '5 0,12 * * *'
jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Install node
      run: |
        curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
        sudo apt-get install -y --no-install-recommends nodejs
    - name: Install required npm packages
      run: |
        sudo npm -g config set user root \
        && sudo npm install -g canvas \
        && sudo npm install -g vega vega-lite vega-cli
    - name: Update data
      run: python get_rates.py
    - name: Update graphs
      run: python graphs.py
    - name: Update README
      run: python update_readme.py --rewrite
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Scheduled data update"
        add: "data/*.csv img/*.png README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}